---
- name: uninstall the packages
  hosts: all
  become: true
  vars:
    packages:
      - git
      - httpd
  tasks:
    - name: remove the packages
      yum:
        name: "{{packages}}"
        state: absent
